import { NextResponse } from 'next/server';

export async function GET() {
  // Dados mock de bairros com coordenadas reais do Brasil
  const neighborhoods = [
    {
      id: 'bairro-1',
      name: 'Centro',
      city: 'Rio de Janeiro',
      state: 'RJ',
      lat: -22.9068,
      lng: -43.1729,
      clients: 45,
      revenue: 125000,
      coverage: 78,
      potential: 180000,
      competitors: 3,
    },
    {
      id: 'bairro-2',
      name: 'Copacabana',
      city: 'Rio de Janeiro',
      state: 'RJ',
      lat: -22.9829,
      lng: -43.1899,
      clients: 32,
      revenue: 98000,
      coverage: 65,
      potential: 150000,
      competitors: 5,
    },
    {
      id: 'bairro-3',
      name: 'Ipanema',
      city: 'Rio de Janeiro',
      state: 'RJ',
      lat: -22.9868,
      lng: -43.2025,
      clients: 28,
      revenue: 87000,
      coverage: 58,
      potential: 140000,
      competitors: 4,
    },
    {
      id: 'bairro-4',
      name: 'Leblon',
      city: 'Rio de Janeiro',
      state: 'RJ',
      lat: -22.9971,
      lng: -43.2256,
      clients: 35,
      revenue: 105000,
      coverage: 72,
      potential: 160000,
      competitors: 3,
    },
    {
      id: 'bairro-5',
      name: 'Barra da Tijuca',
      city: 'Rio de Janeiro',
      state: 'RJ',
      lat: -23.0155,
      lng: -43.3667,
      clients: 22,
      revenue: 65000,
      coverage: 45,
      potential: 200000,
      competitors: 2,
    },
    {
      id: 'bairro-6',
      name: 'Niterói Centro',
      city: 'Niterói',
      state: 'RJ',
      lat: -22.8833,
      lng: -43.1,
      clients: 18,
      revenue: 52000,
      coverage: 38,
      potential: 95000,
      competitors: 2,
    },
    {
      id: 'bairro-7',
      name: 'São Gonçalo Centro',
      city: 'São Gonçalo',
      state: 'RJ',
      lat: -22.8333,
      lng: -43.05,
      clients: 12,
      revenue: 35000,
      coverage: 28,
      potential: 85000,
      competitors: 1,
    },
    {
      id: 'bairro-8',
      name: 'Duque de Caxias Centro',
      city: 'Duque de Caxias',
      state: 'RJ',
      lat: -22.7833,
      lng: -43.3,
      clients: 15,
      revenue: 42000,
      coverage: 32,
      potential: 110000,
      competitors: 1,
    },
  ];

  return NextResponse.json({
    success: true,
    data: neighborhoods,
    timestamp: new Date().toISOString(),
  });
}
